config/routes.rb
StudentCmsRails::Application.routes.draw do
  resources :socials

  resources :students

  resources :apps

end

app/models/app.rb
class App < ActiveRecord::Base
  # attr_accessible :title, :body

  belongs_to :student

end

app/models/social.rb
class Social < ActiveRecord::Base
  # attr_accessible :title, :body

  belongs_to :student

end

app/models/student.rb
class Student < ActiveRecord::Base
  # attr_accessible :title, :body


  has_many :apps, :foreign_key => "students_id"
  has_many :socials, :foreign_key => "students_id"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(params[:app])

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render json: @app, status: :created, location: @app }
      else
        format.html { render action: "new" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/socials_controller.rb
class SocialsController < ApplicationController
  # GET /socials
  # GET /socials.json
  def index
    @socials = Social.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @socials }
    end
  end

  # GET /socials/1
  # GET /socials/1.json
  def show
    @social = Social.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @social }
    end
  end

  # GET /socials/new
  # GET /socials/new.json
  def new
    @social = Social.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @social }
    end
  end

  # GET /socials/1/edit
  def edit
    @social = Social.find(params[:id])
  end

  # POST /socials
  # POST /socials.json
  def create
    @social = Social.new(params[:social])

    respond_to do |format|
      if @social.save
        format.html { redirect_to @social, notice: 'Social was successfully created.' }
        format.json { render json: @social, status: :created, location: @social }
      else
        format.html { render action: "new" }
        format.json { render json: @social.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /socials/1
  # PUT /socials/1.json
  def update
    @social = Social.find(params[:id])

    respond_to do |format|
      if @social.update_attributes(params[:social])
        format.html { redirect_to @social, notice: 'Social was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @social.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /socials/1
  # DELETE /socials/1.json
  def destroy
    @social = Social.find(params[:id])
    @social.destroy

    respond_to do |format|
      format.html { redirect_to socials_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])
    @socials = @student.socials

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/socials_helper.rb
module SocialsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentCmsRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/socials/_form.html.erb
<%= form_for(@social) do |f| %>
  <% if @social.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@social.errors.count, "error") %> prohibited this social from being saved:</h2>

      <ul>
      <% @social.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/socials/edit.html.erb
<h1>Editing social</h1>

<%= render 'form' %>

<%= link_to 'Show', @social %> |
<%= link_to 'Back', socials_path %>

app/views/socials/index.html.erb
<h1>Listing socials</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @socials.each do |social| %>
  <tr>
    <td><%= link_to 'Show', social %></td>
    <td><%= link_to 'Edit', edit_social_path(social) %></td>
    <td><%= link_to 'Destroy', social, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Social', new_social_path %>

app/views/socials/new.html.erb
<h1>New social</h1>

<%= render 'form' %>

<%= link_to 'Back', socials_path %>

app/views/socials/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_social_path(@social) %> |
<%= link_to 'Back', socials_path %>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div id="page">
  <header id="header">
    <div class="center">
      <nav id="main-menu">
        <ul>
          <li class="site-title"><a href="index.html">Students @ Flatiron School</a></li>
        </ul>
        <ul>
          <li><a href="http://flatironschool.com">More about Our School</a></li>
        </ul>
      </nav>
      <div class="clear"></div>
    </div>
  </header>

  <section id="about" class="about-us content">
    <div class="center">
      <h1 id="intro" style="padding-top: 20px">
        Every story has heroes. We're 20 people on a journey to learn to love code.
      </h1>
      <!-- <h2 class="title"><span>The Heroes</span></h2> -->
      <div class="columns">
        <% @students.each do |student| %>
           <% if (student.id) % 3 == 0 %>
             <div class="one_third last">
          <% else %>
             <div class="one_third">
          <% end %>
              <div class="name-position">
                <h2><%= link_to student.name, student %></h2>
                <div class="position"><%= student.catchphrase %></div>
              </div>
              <div class="clear"></div>
            </a>
            <p class="excerpt"><%= student.introduction %></p>
          </div>

          <% if (student.id) % 3 == 0 %>
          <div class="clear"></div> 
          <% end %>
        <% end %>
        

      </div>
      <div class="clear"></div>
    </div>
    <!-- /END .center-->
  </section>
  <!-- /END #about-us -->


   <section id="copyright" class="footer content">
    <div class="center">
      <p>&copy; 2012. All Your Rights Are Belong To Us.</p>
      <div class="clear"></div>
    </div>
  </section>
</div>
<!--/border-->
<div id="left-border"></div>
<div id="right-border"></div>
<div id="top-border"></div>
<div id="bottom-border"></div>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

<div id="page">
  <header id="header">
    <div class="center">
      <nav id="main-menu">
        <ul>
          <li class="site-title" style="font-size: 3em; padding-bottom: 10px">The Flatiron School</li>
        </ul>

        <ul>
          <li><a class="menu" href="http://flatironschool.com/#home">About</a></li>
          <li><a class="menu" href="http://flatironschool.com/#program">The Program</a></li>
          <li><a class="menu" href="http://flatironschool.com/#profile">Graduate Profile</a></li>
          <li><a class="menu" href="http://flatironschool.com/#sponsor">Get Involved</a></li>
          <li><a href="http://eepurl.com/nTXCr" target="_blank" style="color: red">&#10029; Apply &#10029;</a></li>
          <li><a class="menu" href="http://flatironschool.com/#people">Our People</a></li>
          <li><a class="menu" href="http://flatironschool.com/#faq">FAQ</a></li>
          <li><a class="menu" href="http://flatironschool.com/#contact">Get In Touch</a></li>
          <li><a href="http://blog.flatironschool.com">Weblog</a></li>
        </ul>
      </nav>
      <ul id="filter" class="mobile-ipad-menu">
        <li id="top"><a class="top-link">Home</a>
          <ul id="controls">
            <li><a href="http://eepurl.com/nTXCr" class="visualNav menu">Apply</a></li>
            <li><a href="http://flatironschool.com/#home" class="visualNav menu">About</a>
            <!-- <li><a href="http://flatironschool.com/#philosophy" class="visualNav">Philosophy</a></li> -->
            <li><a href="http://flatironschool.com/#program" class="visualNav menu">The Program</a></li>
            <li><a href="http://flatironschool.com/#sponsor" class="visualNav">Get Involved</a></li>
            <li><a href="http://flatironschool.com/#faq" class="visualNav">FAQ</a></li>
            <li><a href="http://flatironschool.com/#people" class="visualNav menu">Our People</a></li>
            <li><a href="http://flatironschool.com/#contact" class="visualNav menu">Get In Touch</a></li>
            <li><a href="http://blog.flatironschool.com">Weblog</a></li>
          </ul>
        </li>
      </ul>

      <div class="clear"></div>
    </div>
  </header>

  <section id="about" class="about-us content" style="margin-top: 34px">


        <div class="jrcolumns">
          <!-- LEFT COLUMN -->
          <div id='navcontainer'class="one_third">


  

<div class="profile-photo">
  <img src="<%= @student.photo %>"/>
</div>

    <nav id='side-nav'>
      <ul>
          <% @left_nav = ["email", "blog", "linkedin", "twitter"] %>
          <% @left_nav.each do |item| %>
            <li class='<%= @socials.find_by_name("#{item}").name %>'>
            <a href='<%= @socials.find_by_name("#{item}").link %>'><%= @socials.find_by_name("#{item}").name.capitalize %></a>
            </li>
          <% end %>
      </ul>
    </nav> <!-- this is the end of side nav -->
  </div>
  <!-- MIDDLE COLUMN -->
  <div class="two_third">
    <h1><%= @student.name %></h1>
    <h2 id='tagline'><%= @student.tagline %></h2>
    <p><%= @student.bio %></p>

    <br/><br/>
    <h2 id='tagline'>My favorite apps</h2>

      <% @student.apps.each do |app| %>
        <% if app.id % 3 == 0 %>
          <div class="one_third last">
        <% else %>
          <div class="one_third">
        <% end %>
          <h4><%= app.name %></h4>
          <p><%= app.description %></p>
        </div>
      <% end %>


  </div>
          <!-- RIGHT COLUMN -->

        <div class="clear"></div>

        <h2 class="title"><span>Coder Cred</span></h2>



          <div class="columns" style="padding-left: 22px;">
          <div class="coder-cred">
              <% @social_links = ["github", "codeschool", "coderwall", "stackoverflow", "treehouse"] %>
              <% @social_links.each do |item| %>
                <% if @socials.find_by_name("#{item}").id % 5 == 0 %>
                  <div class="one_fifth last">
                <% else %>
                  <div class="one_fifth">
                <% end %>
                  <a href="<%= @socials.find_by_name("#{item}").link %>">
                    <div class="cred-<%= @socials.find_by_name("#{item}").name %>"></div>
                  </a>
                </div>
              <% end %> 
          </div>
          </div>


        <div class="clear"></div>
        <h2 class="title"><span>Social Nerdery</span></h2>


        <div class="one_half">

          <h2> Github Feed</h2>

          <% username = @socials.find_by_name("github").link.split('github.com/')[1] %>
            <script language="JavaScript" src="http://itde.vccs.edu/rss2js/feed2js.php?src=https%3A%2F%2Fgithub.com%2F<%= username %>.atom&chan=n&num=5&desc=1&date=n&targ=y" type="text/javascript"></script>

            <noscript>
            <a href="http://itde.vccs.edu/rss2js/feed2js.php?src=https%3A%2F%2Fgithub.com%2Fcreekace.atom&chan=n&num=5&desc=1&date=n&targ=y&html=y">View RSS feed</a>
            </noscript>


        </div>

        <div class="one_half last">
          <% if @socials.find_by_name("twitter") %>
            <a class="twitter-timeline" href="<%= @socials.find_by_name("twitter").link %>" data-widget-id="<%= @student.twitter_widget_id.to_s %>">Tweets by @<%= @socials.find_by_name("twitter").link.match(".com\/(.+)")[1] %></a>
              <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="http://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>  
          <% else %>
            <h3>This crazy guy doesn't use twitter!</h3>
          <% end %>


        </div>
        <div class="clear"></div>
        <h2 class="title">&nbsp;</h2>
      </div>
    </div>
  </section>